/**
 * Example stories for the landing showcase (research → direction → post).
 *
 * GENERATED by api/scripts/generate_landing_examples.py with the app's own post-writing
 * stack and HEBREW_STYLE, then hand-reviewed against web/HEBREW-COPY.md. Every business
 * here is fictional: invented names and facts, no real brand, logo or person.
 * Re-running the script overwrites the hand fixes, so review the diff.
 */

import type { BrandSwatch } from "@/lib/api";
import type { CardTemplate } from "@/components/CardCanvas";

export type LandingExample = {
  slug: string;
  /** The short business type on the showcase tab, e.g. "מאפייה". */
  pill: string;
  businessName: string;
  typeLabel: string;
  city: string;
  /** Where the (fictional) research looked. Shown as plain words, never as integrations. */
  sources: string[];
  /** "מה גילינו": one observation, phrased as something seen or an assumption to test. */
  insight: string;
  /** "הכיוון לחודש": what the month does because of the insight. */
  direction: string;
  /** What gets checked at the end of the month to know whether the direction held. */
  check: string;
  palette: BrandSwatch[];
  template: CardTemplate;
  /** A photo generated with AI for this fictional business, or null for a typographic card. */
  image: string | null;
  post: {
    format: "image";
    hook: string;
    caption: string;
    cta: string;
    overlayHeadline: string;
    overlayBadge: string;
  };
  why: { audience: string; goal: string; timing: string; reason: string };
};

export const LANDING_EXAMPLES: LandingExample[] = [
  {
    "slug": "bakery",
    "pill": "מאפייה",
    "businessName": "פרג ושמרים",
    "typeLabel": "מאפייה שכונתית",
    "city": "כפר סבא",
    "sources": ["האתר", "אינסטגרם", "לוח השנה"],
    "insight": "בחנוכה שעבר ההזמנות לגנים הגיעו בוואטסאפ, ברגע האחרון.",
    "direction": "פותחים הזמנות מראש לגנים בוואטסאפ, ומראים כל בוקר את הטיגון.",
    "check": "כמה הזמנות לגנים הגיעו מראש",
    "palette": [
      { "hex": "#6b3f24", "role": "primary", "name": "קרום אפוי" },
      { "hex": "#e0a42b", "role": "accent", "name": "חרדל" },
      { "hex": "#f6ecd9", "role": "background", "name": "קמח" },
      { "hex": "#2a1a10", "role": "ink", "name": "קפה" }
    ],
    "template": "lower_editorial",
    "image": "/examples/bakery.webp",
    "post": {
      "format": "image",
      "hook": "מטגנים כל בוקר במקום. ריבת חלב או תות ביתית.",
      "caption": "לגן ולמסיבה של חנוכה מזמינים מראש בוואטסאפ, ואוספים בלי התור שמגיע עד הרחוב.",
      "cta": "מזמינים בוואטסאפ",
      "overlayHeadline": "מטגנים כל בוקר, אוספים בלי תור",
      "overlayBadge": "חנוכה"
    },
    "why": {
      "audience": "הורים בשכונה",
      "goal": "הזמנות מראש לגנים",
      "timing": "שבועיים לפני חנוכה",
      "reason": "פוסט שמתפרסם שבועיים לפני חנוכה נותן להורים זמן להזמין מראש בוואטסאפ."
    }
  },
  {
    "slug": "lingerie",
    "pill": "הלבשה תחתונה",
    "businessName": "תפר עדין",
    "typeLabel": "הלבשה תחתונה ומידות",
    "city": "חיפה",
    "sources": ["אינסטגרם", "פייסבוק", "לוח השנה"],
    "insight": "בפייסבוק לקוחות כותבות שחזייה שהזמינו מאתר גדול לא ישבה טוב.",
    "direction": "מזמינים למדידה אישית, לפני שקונים עוד חזייה אונליין.",
    "check": "כמה נשים קבעו מדידה",
    "palette": [
      { "hex": "#5a2a45", "role": "primary", "name": "שזיף" },
      { "hex": "#e8b4a8", "role": "accent", "name": "אבקה" },
      { "hex": "#f7ece9", "role": "background", "name": "תחרה" },
      { "hex": "#2b1420", "role": "ink", "name": "שזיף כהה" }
    ],
    "template": "split_panel",
    "image": "/examples/lingerie.webp",
    "post": {
      "format": "image",
      "hook": "כמה חזיות הזמנתן אונליין ונשארו במגירה?",
      "caption": "הרבה לקוחות מגלות אצלנו שהן לובשות מידה לא נכונה. מודדות בחדר סגור, בסבלנות ובלי לחץ לקנות. לפני הקנייה הבאה באתר, קבעו מדידה בחיפה.",
      "cta": "קובעים מדידה",
      "overlayHeadline": "קודם מודדות, אחר כך קונות",
      "overlayBadge": "בלאק פריידי"
    },
    "why": {
      "audience": "נשים שקונות חזיות אונליין",
      "goal": "מדידות בחנות",
      "timing": "שבוע לפני בלאק פריידי",
      "reason": "לפני בלאק פריידי קונים חזיות באתרים. הפוסט מזמין למדוד קודם, בחנות."
    }
  },
  {
    "slug": "beauty",
    "pill": "קוסמטיקה",
    "businessName": "מרווה",
    "typeLabel": "קוסמטיקה וטיפולי פנים",
    "city": "מודיעין",
    "sources": ["האתר", "אינסטגרם"],
    "insight": "רוב השאלות בהודעות באינסטגרם הן על עור יבש ומגרד.",
    "direction": "מסבירים החודש מה קורה בפגישה הראשונה, לעור יבש ורגיש.",
    "check": "כמה הודעות על עור יבש הגיעו",
    "palette": [
      { "hex": "#4f6b58", "role": "primary", "name": "מרווה" },
      { "hex": "#c8a96a", "role": "accent", "name": "דבש" },
      { "hex": "#eef1ea", "role": "background", "name": "עלה בהיר" },
      { "hex": "#1f2a22", "role": "ink", "name": "יער" }
    ],
    "template": "framed_inset",
    "image": "/examples/beauty.webp",
    "post": {
      "format": "image",
      "hook": "הדלקתם חימום, והעור מתחיל למשוך ולגרד?",
      "caption": "רואים את זה כל חורף. בפגישה הראשונה בודקים את העור ובונים איתכם שגרה פשוטה לבית. שלחו הודעה ונגיד אם זה מתאים לכם.",
      "cta": "שולחים הודעה",
      "overlayHeadline": "עור יבש מהחימום? מתחילים בפגישה אחת",
      "overlayBadge": "חורף"
    },
    "why": {
      "audience": "נשים עם עור יבש בחורף",
      "goal": "פניות לפגישה ראשונה",
      "timing": "הימים הקרים הראשונים",
      "reason": "עם החימום הראשון העור מתייבש, והפוסט עונה על השאלה שהכי הרבה שואלים בהודעות."
    }
  },
  {
    "slug": "accountant",
    "pill": "הנהלת חשבונות",
    "businessName": "ספרות",
    "typeLabel": "הנהלת חשבונות לעצמאים",
    "city": "תל אביב",
    "sources": ["האתר", "פייסבוק", "לוח השנה"],
    "insight": "בקבוצות עצמאים בפייסבוק חוזרת כל דצמבר השאלה: מה עוד אפשר להוציא לפני סוף השנה.",
    "direction": "מסבירים לעצמאים חדשים אילו הוצאות מוכרות, לפני שהשנה נסגרת.",
    "check": "כמה שיחות היכרות נקבעו",
    "palette": [
      { "hex": "#1f2f4a", "role": "primary", "name": "כחול כהה" },
      { "hex": "#f2c14e", "role": "accent", "name": "צהוב מרקר" },
      { "hex": "#f4f5f7", "role": "background", "name": "נייר" },
      { "hex": "#121a28", "role": "ink", "name": "דיו" }
    ],
    "template": "cover_type",
    "image": "/examples/accountant.webp",
    "post": {
      "format": "image",
      "hook": "מה שתשלמו עד 31 בדצמבר נכנס לדוח של השנה הזאת.",
      "caption": "עצמאים בשנה הראשונה שואלים אותנו הרבה מה מוכר ומה לא. בשיחת היכרות בטלפון, בלי התחייבות, נעשה לכם סדר. כתבו לנו לפני שהשנה נסגרת.",
      "cta": "כותבים לנו בוואטסאפ",
      "overlayHeadline": "מה עוד מוכר לפני סוף השנה",
      "overlayBadge": "סוף שנה"
    },
    "why": {
      "audience": "עצמאים בשנה הראשונה",
      "goal": "שיחות היכרות",
      "timing": "דצמבר, לפני שהשנה נסגרת",
      "reason": "בדצמבר כל עצמאי חדש שואל מה עוד מוכר. הפוסט עונה, ומזמין לשיחה."
    }
  },
  {
    "slug": "yoga",
    "pill": "יוגה",
    "businessName": "סטודיו נשימה",
    "typeLabel": "יוגה ופילאטיס",
    "city": "פרדס חנה",
    "sources": ["אינסטגרם", "טיקטוק", "לוח השנה"],
    "insight": "מתחילים כותבים בהודעות שהם מפחדים להיות הכי פחות גמישים בחדר.",
    "direction": "מראים כל החודש שמתחילים בלי גמישות ובלי ניסיון.",
    "check": "כמה נרשמו לסדרה למתחילים",
    "palette": [
      { "hex": "#b5573a", "role": "primary", "name": "טרקוטה" },
      { "hex": "#e9c9a0", "role": "accent", "name": "חול" },
      { "hex": "#f7efe6", "role": "background", "name": "פשתן" },
      { "hex": "#2f2520", "role": "ink", "name": "אדמה" }
    ],
    "template": "split_panel",
    "image": "/examples/yoga.webp",
    "post": {
      "format": "image",
      "hook": "לא צריך גמישות ולא ניסיון. רק מזרן.",
      "caption": "הקבוצות קטנות, והמורה מכירה כל אחד בשם. הסדרה למתחילים נפתחת בתחילת ינואר, בערב. כתבו לנו בהודעה ונשמור לכם מקום.",
      "cta": "שומרים מקום",
      "overlayHeadline": "לא צריך גמישות, רק מזרן",
      "overlayBadge": "ינואר"
    },
    "why": {
      "audience": "מי שמפחדים לא לעמוד בקצב",
      "goal": "הרשמות לסדרה למתחילים",
      "timing": "תחילת ינואר",
      "reason": "בינואר מתחילים שגרה חדשה, והפוסט עונה על הפחד שמתחילים כותבים עליו בהודעות."
    }
  },
  {
    "slug": "ceramics",
    "pill": "קרמיקה",
    "businessName": "כד וכוס",
    "typeLabel": "קרמיקה בעבודת יד, חנות אונליין",
    "city": "משלוחים לכל הארץ",
    "sources": ["האתר", "אינסטגרם", "טיקטוק"],
    "insight": "בטיקטוק, סרטונים של ידיים על האובניים נצפים יותר מתמונה של כלי גמור.",
    "direction": "לפני ההשקה מראים איך נולדים ספלי החורף, על האובניים.",
    "check": "כמה שמרו ושיתפו את הסרטונים",
    "palette": [
      { "hex": "#2b4b5c", "role": "primary", "name": "ים בחורף" },
      { "hex": "#d9774b", "role": "accent", "name": "חימר" },
      { "hex": "#f1ede6", "role": "background", "name": "גלזורה" },
      { "hex": "#16252d", "role": "ink", "name": "צפחה" }
    ],
    "template": "lower_editorial",
    "image": "/examples/ceramics.webp",
    "post": {
      "format": "image",
      "hook": "אין שני ספלים זהים. תראו איך זה נולד.",
      "caption": "אנחנו מסיימים עכשיו את סדרת החורף, בגוונים של ים בחורף. היא עולה לאתר ביום ראשון, בכמות קטנה. שלחו את זה למי שאוהבים תה חם.",
      "cta": "שולחים למי שאוהב תה",
      "overlayHeadline": "אין שני ספלים זהים",
      "overlayBadge": "סדרת החורף"
    },
    "why": {
      "audience": "מי שאוהבים כלים יפים לבית",
      "goal": "שיותר אנשים יכירו את העסק",
      "timing": "ימים לפני ההשקה",
      "reason": "מי שלא מכיר אתכם נעצר על ידיים שעובדות, ומגיע ליום ההשקה כבר מכיר."
    }
  },
  {
    "slug": "interior",
    "pill": "עיצוב פנים",
    "businessName": "קו אופק",
    "typeLabel": "עיצוב פנים לדירות קטנות",
    "city": "רמת גן",
    "sources": ["אינסטגרם", "פייסבוק"],
    "insight": "בקבוצות של דירה ראשונה בפייסבוק שואלים איך מכניסים שולחן אוכל לסלון קטן.",
    "direction": "כל שבוע לפני ואחרי: איפה שמים שולחן בסלון קטן.",
    "check": "שמירות ובקשות לפגישת ייעוץ",
    "palette": [
      { "hex": "#2e2e2c", "role": "primary", "name": "פחם" },
      { "hex": "#8a8f5a", "role": "accent", "name": "זית" },
      { "hex": "#efebe4", "role": "background", "name": "טיח" },
      { "hex": "#1b1b1a", "role": "ink", "name": "גרפיט" }
    ],
    "template": "framed_inset",
    "image": "/examples/interior.webp",
    "post": {
      "format": "image",
      "hook": "הבעיה היא לא הגודל. זה איפה שמתם את השולחן.",
      "caption": "אירחתם את כולם בחגים ולא היה איפה לשבת? בפגישת ייעוץ אחת בבית אנחנו יוצאים עם רשימה ברורה של מה להזיז. הרבה פעמים זה רק עניין של איפה השולחן עומד.",
      "cta": "כותבים לנו בוואטסאפ",
      "overlayHeadline": "איפה לשים את השולחן",
      "overlayBadge": "אחרי החגים"
    },
    "why": {
      "audience": "זוגות צעירים בדירה ראשונה",
      "goal": "שיכירו אתכם כמומחים",
      "timing": "מיד אחרי אירוח החגים",
      "reason": "אחרי החגים כולם הרגישו כמה הסלון צפוף. טיפ מעשי מציג אתכם כמומחים."
    }
  },
  {
    "slug": "cabins",
    "pill": "צימרים",
    "businessName": "עננה",
    "typeLabel": "צימרים בגליל העליון",
    "city": "הגליל העליון",
    "sources": ["האתר", "אינסטגרם", "לוח השנה"],
    "insight": "באינסטגרם, סרטון של האח הדולקת קיבל יותר תגובות מכל תמונת נוף.",
    "direction": "מראים כל שבוע את האח הדולקת, לפני סופי השבוע הגשומים.",
    "check": "כמה פניות לסופ״ש הגיעו בוואטסאפ",
    "palette": [
      { "hex": "#2f4b3b", "role": "primary", "name": "אורן" },
      { "hex": "#d4a248", "role": "accent", "name": "אש באח" },
      { "hex": "#f2efe7", "role": "background", "name": "ערפל" },
      { "hex": "#18241d", "role": "ink", "name": "יער בלילה" }
    ],
    "template": "cover_type",
    "image": "/examples/cabins.webp",
    "post": {
      "format": "image",
      "hook": "העצים כבר ליד האח. מהמרפסת רואים את העננים על ההר.",
      "caption": "בחורף, כשיורד גשם, העננים יורדים עד המרפסת. ארוחת הבוקר מגיעה לבקתה בסלסלה. כתבו לנו בוואטסאפ לסופ״ש של גשם.",
      "cta": "כותבים לנו בוואטסאפ",
      "overlayHeadline": "האח דולקת, העננים על ההר",
      "overlayBadge": "סופ״ש גשום"
    },
    "why": {
      "audience": "זוגות שמחפשים סופ״ש שקט",
      "goal": "הזמנות לסופי שבוע",
      "timing": "לפני סופי השבוע הגשומים",
      "reason": "זוגות מזמינים חורף שבועיים מראש, והאח הדולקת היא מה שעצר אותם באינסטגרם."
    }
  }
];
