/**
 * A mini 3-month plan per showcase business ("בחרו עסק וראו את התוכנית שלו"), in the shape
 * of the plan the product builds (docs/onboarding-v2.md, Revision 5): the strategy in one
 * line, the main measure and what it needs connected, channels (existing and new), the
 * budget split per month, three months with a key date and an example post title each,
 * and the bet the plan is testing.
 *
 * HAND-WRITTEN against web/HEBREW-COPY.md, and kept apart from examples.ts on purpose:
 * that file is regenerated by api/scripts/generate_landing_examples.py, which would wipe
 * these fields. Keyed by the example's slug.
 *
 * Every business is FICTIONAL. Honesty rules, the same as the product's:
 * - budgets are ranges, and they follow the product's own budget stages (web/lib/budget.ts,
 *   api/app/services/cost_model.py): under 2,500 ₪ a month paid media only goes to people
 *   who already know the business, so only the two businesses at 3,000–7,000 ₪ pay to
 *   reach new people, and nobody gets search ads below the sector floor;
 * - no results, no follower counts, no "up to X% more": the plan says what it measures,
 *   never what it will achieve;
 * - key dates are real calendar moments (Hanukkah, Black Friday, 31 December) or plainly
 *   the business's own (a launch day), never an invented public event.
 */

export type IntegrationKey = "ga4" | "meta_pixel" | "gtm" | "search_console" | "gbp" | "meta_business" | "whatsapp_link";

/** have: already there · connect: one click on our side · install: a snippet on the site · ready: nothing to do. */
export type IntegrationStatus = "have" | "connect" | "install" | "ready";

export const INTEGRATION_NAMES: Record<IntegrationKey, string> = {
  ga4: "נתוני האתר",
  meta_pixel: "הפיקסל של פייסבוק",
  gtm: "התג של גוגל באתר",
  search_console: "החיפושים בגוגל",
  gbp: "הכרטיס של העסק בגוגל",
  meta_business: "אינסטגרם ופייסבוק",
  whatsapp_link: "קישור וואטסאפ",
};

export const STATUS_LABELS: Record<IntegrationStatus, string> = {
  have: "יש לכם",
  connect: "צריך לחבר",
  install: "צריך להתקין באתר",
  ready: "בלי התקנה",
};

export type PostFormat = "פוסט" | "ריל" | "קרוסלה" | "סטורי" | "סרטון";

export type PlanMonth = {
  /** What the month is about, in a few words. */
  focus: string;
  /** The one date the month is built around, or null for a month without one. */
  date: string | null;
};

/**
 * Content types the plan splits posts into. A strategist sets the structure; which
 * products to feature in each post is the owner's decision inside the app (stock, margin).
 */
export type MixType = "product" | "value" | "behind_scenes" | "social_proof" | "offer" | "community" | "seasonal";

export const MIX_LABELS: Record<MixType, string> = {
  product: "מוצרים ושירותים",
  value: "תוכן שמלמד",
  behind_scenes: "מאחורי הקלעים",
  social_proof: "לקוחות מספרים",
  offer: "הזמנה לפעולה",
  community: "קהילה",
  seasonal: "חגים ועונות",
};

export type LandingPlan = {
  /** "האסטרטגיה": the plan in one line. */
  strategy: string;
  /** "מה נמדוד": the main measure, and how it is counted. */
  kpi: { name: string; how: string };
  integrations: { key: IntegrationKey; status: IntegrationStatus }[];
  channels: { name: string; kind: "existing" | "new"; startsMonth: 1 | 2 | 3 }[];
  /**
   * The owner's monthly range and the split per month. `lines[j].months[m]` is the range
   * in shekels for line j in month m. `lines` empty = organic only, and `unlock` says what
   * a budget would add.
   */
  budget: {
    range: string;
    lines: { name: string; months: [number, number][] }[];
    unlock?: string;
  };
  months: [PlanMonth, PlanMonth, PlanMonth];
  /** "תמהיל התוכן": how the posts split by type, in percent (sums to 100). */
  mix: { type: MixType; share: number }[];
  /** "ההשערה שנבדוק": the hypothesis, and what changes if it is not confirmed. */
  bet: { bet: string; ifWrong: string };
};

export const LANDING_PLANS: Record<string, LandingPlan> = {
  bakery: {
    strategy: "להפוך את חנוכה מתור של הרגע האחרון להזמנות מראש מהגנים.",
    kpi: { name: "הזמנות מראש לגנים", how: "כל הזמנה בקישור הוואטסאפ נספרת" },
    integrations: [
      { key: "whatsapp_link", status: "ready" },
      { key: "gbp", status: "connect" },
      { key: "meta_business", status: "connect" },
    ],
    channels: [
      { name: "אינסטגרם", kind: "existing", startsMonth: 1 },
      { name: "וואטסאפ", kind: "existing", startsMonth: 1 },
      { name: "ועדי הורים בגנים", kind: "new", startsMonth: 1 },
      { name: "הכרטיס של העסק בגוגל", kind: "new", startsMonth: 2 },
    ],
    budget: {
      range: "1,000–3,000 ₪",
      lines: [
        { name: "קידום למי שכבר מכיר אתכם", months: [[400, 700], [900, 1500], [300, 500]] },
        { name: "עלונים לגנים בשכונה", months: [[150, 300], [100, 200], [0, 0]] },
      ],
    },
    months: [
      { focus: "פותחים הזמנות מראש לגנים", date: null },
      { focus: "חנוכה: טיגון כל בוקר", date: "חנוכה" },
      { focus: "פירות יבשים לט״ו בשבט", date: "ט״ו בשבט" },
    ],
    mix: [{ type: "product", share: 40 }, { type: "seasonal", share: 25 }, { type: "behind_scenes", share: 20 }, { type: "community", share: 15 }],
    bet: { bet: "הגנים יזמינו מראש אם יהיה קישור אחד לוואטסאפ.", ifWrong: "מדברים ישירות עם ועדי ההורים." },
  },

  lingerie: {
    strategy: "להיות המקום בחיפה שבו קודם מודדות, ורק אחר כך קונות.",
    kpi: { name: "מדידות שנקבעו", how: "לפי ההודעות בוואטסאפ ובאינסטגרם" },
    integrations: [
      { key: "whatsapp_link", status: "ready" },
      { key: "meta_business", status: "connect" },
      { key: "gbp", status: "have" },
    ],
    channels: [
      { name: "אינסטגרם", kind: "existing", startsMonth: 1 },
      { name: "פייסבוק", kind: "existing", startsMonth: 1 },
      { name: "הכרטיס של העסק בגוגל", kind: "existing", startsMonth: 1 },
      { name: "רשימת תפוצה בוואטסאפ", kind: "new", startsMonth: 2 },
    ],
    budget: {
      range: "1,000–3,000 ₪",
      lines: [
        { name: "קידום למי שכבר מכיר אתכם", months: [[500, 900], [1000, 1800], [400, 800]] },
        { name: "צילום בחנות", months: [[400, 800], [0, 0], [0, 0]] },
      ],
    },
    months: [
      { focus: "למה חזייה מאתר לא יושבת טוב", date: null },
      { focus: "לפני המבצעים: קודם מודדות", date: "בלאק פריידי" },
      { focus: "מי שמדדה מצטרפת לרשימה", date: null },
    ],
    mix: [{ type: "product", share: 35 }, { type: "value", share: 30 }, { type: "social_proof", share: 20 }, { type: "offer", share: 15 }],
    bet: { bet: "נשים יבואו למדידה אם יידעו שאין לחץ לקנות.", ifWrong: "מציעים קודם שיחה קצרה בוואטסאפ." },
  },

  beauty: {
    strategy: "להיות הכתובת במודיעין לעור יבש ורגיש בחורף.",
    kpi: { name: "פניות לפגישה ראשונה", how: "הודעות באינסטגרם ובקישור הוואטסאפ" },
    integrations: [
      { key: "meta_business", status: "connect" },
      { key: "whatsapp_link", status: "ready" },
      { key: "ga4", status: "install" },
    ],
    channels: [
      { name: "אינסטגרם", kind: "existing", startsMonth: 1 },
      { name: "האתר", kind: "existing", startsMonth: 1 },
      { name: "הכרטיס של העסק בגוגל", kind: "new", startsMonth: 1 },
      { name: "רשימת תפוצה בוואטסאפ", kind: "new", startsMonth: 3 },
    ],
    budget: {
      range: "1,000–3,000 ₪",
      lines: [
        { name: "קידום למי שכבר מכיר אתכם", months: [[500, 900], [700, 1200], [500, 900]] },
        { name: "שוברי מתנה מודפסים", months: [[0, 0], [150, 300], [0, 0]] },
      ],
    },
    months: [
      { focus: "מה קורה בפגישה הראשונה", date: "הימים הקרים הראשונים" },
      { focus: "שובר מתנה לטיפול פנים", date: "חנוכה" },
      { focus: "שגרה לבית, לאמצע החורף", date: null },
    ],
    mix: [{ type: "value", share: 40 }, { type: "social_proof", share: 25 }, { type: "product", share: 20 }, { type: "behind_scenes", share: 15 }],
    bet: { bet: "מי ששואלת על עור יבש תקבע פגישה אם תבין מה קורה בה.", ifWrong: "מצלמים פגישה אמיתית, מההתחלה עד הסוף." },
  },

  accountant: {
    strategy: "לענות לעצמאים חדשים על שאלות סוף השנה, לפני שהם שואלים אחרים.",
    kpi: { name: "שיחות היכרות שנקבעו", how: "מהטופס באתר ומקישור הוואטסאפ" },
    integrations: [
      { key: "ga4", status: "have" },
      { key: "meta_pixel", status: "install" },
      { key: "whatsapp_link", status: "ready" },
    ],
    channels: [
      { name: "פייסבוק", kind: "existing", startsMonth: 1 },
      { name: "האתר", kind: "existing", startsMonth: 1 },
      { name: "פרסום בפייסבוק לעצמאים חדשים", kind: "new", startsMonth: 1 },
      { name: "מייל חודשי ללקוחות", kind: "new", startsMonth: 3 },
    ],
    budget: {
      range: "3,000–7,000 ₪",
      lines: [
        { name: "פרסום לעצמאים שעוד לא מכירים אתכם", months: [[2000, 3000], [3000, 4500], [1500, 2500]] },
        { name: "קידום למי שכבר מכיר אתכם", months: [[500, 800], [700, 1000], [500, 800]] },
      ],
    },
    months: [
      { focus: "הוצאות מוכרות לעצמאים חדשים", date: null },
      { focus: "מה עוד מוכר לפני סוף השנה", date: "31 בדצמבר" },
      { focus: "פותחים שנה מסודרת", date: null },
    ],
    mix: [{ type: "value", share: 55 }, { type: "social_proof", share: 20 }, { type: "product", share: 15 }, { type: "seasonal", share: 10 }],
    bet: { bet: "עצמאי חדש יקבע שיחה אחרי שקיבל תשובה ברורה בחינם.", ifWrong: "מוסיפים מפגש שאלות ותשובות בזום." },
  },

  yoga: {
    strategy: "להראות שכל אחד יכול להתחיל, ולמלא את הסדרה למתחילים.",
    kpi: { name: "הרשמות לסדרה למתחילים", how: "לפי ההודעות וקישור הוואטסאפ" },
    integrations: [
      { key: "meta_business", status: "connect" },
      { key: "whatsapp_link", status: "ready" },
    ],
    channels: [
      { name: "אינסטגרם", kind: "existing", startsMonth: 1 },
      { name: "טיקטוק", kind: "existing", startsMonth: 1 },
      { name: "רשימת תפוצה בוואטסאפ", kind: "new", startsMonth: 1 },
      { name: "שיתוף עם בית הקפה השכונתי", kind: "new", startsMonth: 2 },
    ],
    budget: {
      range: "בלי תקציב פרסום",
      lines: [],
      unlock: "עם 500–1,000 ₪ בחודש אפשר לקדם את הסדרה למי שכבר מכיר אתכם.",
    },
    months: [
      { focus: "מראים שיעור אמיתי למתחילים", date: null },
      { focus: "שיעור פתוח בבית הקפה", date: "חנוכה" },
      { focus: "נפתחת הסדרה למתחילים", date: "תחילת ינואר" },
    ],
    mix: [{ type: "value", share: 30 }, { type: "behind_scenes", share: 25 }, { type: "community", share: 25 }, { type: "offer", share: 20 }],
    bet: { bet: "הפחד מגמישות עוצר יותר אנשים מהמחיר.", ifWrong: "בודקים שיעור ניסיון במחיר מוזל." },
  },

  ceramics: {
    strategy: "למכור את הדרך, לא רק את הספל: מראים איך כל כלי נולד.",
    kpi: { name: "הזמנות באתר", how: "לפי נתוני האתר, לכל ערוץ בנפרד" },
    integrations: [
      { key: "ga4", status: "install" },
      { key: "meta_pixel", status: "install" },
      { key: "meta_business", status: "connect" },
    ],
    channels: [
      { name: "טיקטוק", kind: "existing", startsMonth: 1 },
      { name: "אינסטגרם", kind: "existing", startsMonth: 1 },
      { name: "רשימת מייל להשקות", kind: "new", startsMonth: 1 },
      { name: "קידום הסרטונים", kind: "new", startsMonth: 2 },
    ],
    budget: {
      range: "1,000–3,000 ₪",
      lines: [
        { name: "קידום למי שכבר מכיר אתכם", months: [[0, 0], [1000, 1800], [800, 1500]] },
        { name: "תוכנה לשליחת מיילים", months: [[50, 150], [50, 150], [50, 150]] },
      ],
    },
    months: [
      { focus: "על האובניים: איך נולדים ספלי החורף", date: null },
      { focus: "השקת סדרת החורף", date: "יום ההשקה" },
      { focus: "מתנות בעבודת יד", date: "חנוכה" },
    ],
    mix: [{ type: "behind_scenes", share: 35 }, { type: "product", share: 30 }, { type: "seasonal", share: 20 }, { type: "social_proof", share: 15 }],
    bet: { bet: "מי שראה את הכלי נולד יקנה ביום ההשקה.", ifWrong: "פותחים הזמנה מראש לפני ההשקה הבאה." },
  },

  interior: {
    strategy: "להיות המומחים לדירות קטנות: כל שבוע בעיה אחת, לפני ואחרי.",
    kpi: { name: "בקשות לפגישת ייעוץ", how: "הודעות בקישור הוואטסאפ" },
    integrations: [
      { key: "whatsapp_link", status: "ready" },
      { key: "meta_business", status: "connect" },
      { key: "gbp", status: "connect" },
    ],
    channels: [
      { name: "אינסטגרם", kind: "existing", startsMonth: 1 },
      { name: "קבוצות דירה ראשונה בפייסבוק", kind: "existing", startsMonth: 1 },
      { name: "הכרטיס של העסק בגוגל", kind: "new", startsMonth: 1 },
      { name: "שיתוף עם חנות רהיטים באזור", kind: "new", startsMonth: 2 },
    ],
    budget: {
      range: "1,000–3,000 ₪",
      lines: [
        { name: "קידום למי שכבר מכיר אתכם", months: [[500, 900], [600, 1000], [600, 1000]] },
        { name: "צילום לפני ואחרי", months: [[300, 600], [0, 0], [300, 600]] },
      ],
    },
    months: [
      { focus: "איפה שמים שולחן בסלון קטן", date: "אחרי החגים" },
      { focus: "אחסון בדירה קטנה", date: null },
      { focus: "פינת עבודה בבית", date: "תחילת השנה" },
    ],
    mix: [{ type: "value", share: 45 }, { type: "social_proof", share: 25 }, { type: "behind_scenes", share: 15 }, { type: "product", share: 15 }],
    bet: { bet: "טיפ מעשי אחד בשבוע יביא יותר פניות מתמונות של פרויקטים גמורים.", ifWrong: "חוזרים לפרויקטים, עם הסבר קצר לכל אחד." },
  },

  cabins: {
    strategy: "למכור את החורף בגליל: האח, הגשם והשקט, שבועיים לפני כל סופ״ש.",
    kpi: { name: "פניות לסופ״ש בוואטסאפ", how: "כל פנייה בקישור הוואטסאפ נספרת" },
    integrations: [
      { key: "whatsapp_link", status: "ready" },
      { key: "ga4", status: "have" },
      { key: "meta_pixel", status: "install" },
    ],
    channels: [
      { name: "אינסטגרם", kind: "existing", startsMonth: 1 },
      { name: "האתר", kind: "existing", startsMonth: 1 },
      { name: "פרסום לזוגות שעוד לא מכירים אתכם", kind: "new", startsMonth: 1 },
      { name: "מייל למי שכבר היה אצלכם", kind: "new", startsMonth: 3 },
    ],
    budget: {
      range: "3,000–7,000 ₪",
      lines: [
        { name: "פרסום לזוגות שעוד לא מכירים אתכם", months: [[2000, 3000], [2500, 4000], [1500, 2500]] },
        { name: "קידום למי שכבר מכיר אתכם", months: [[500, 1000], [500, 1000], [500, 1000]] },
      ],
    },
    months: [
      { focus: "האח דולקת: סופי שבוע גשומים", date: "הגשם הראשון" },
      { focus: "חנוכה בגליל", date: "חנוכה" },
      { focus: "סופ״ש זוגי באמצע החורף", date: null },
    ],
    mix: [{ type: "seasonal", share: 30 }, { type: "behind_scenes", share: 25 }, { type: "social_proof", share: 25 }, { type: "offer", share: 20 }],
    bet: { bet: "זוגות מזמינים כשהם רואים את האח, יותר מאשר את הנוף.", ifWrong: "חוזרים לנוף, ובודקים שוב אחרי חודש." },
  },
};
